### ISSUE TITLE
double menu in mobile 

### ISSUE THREAD

**Issue by isjxique** [akhan118/village-green#33]
see two menu bars in mobile and need to get rid of one of them

**Comment by anguess** [comment]
@Nidradee, @TechnoSayge  and Zak will work on completing this issue by Tuesday 1/16/2017

**Comment by TechnoSayge** [comment]
Speaking with nidra:

Go to code...seek comment, get rid of duplicate in front end.  Testing front end and clicking on boxes...there is a modal that needs to be taken out (let's find it)...overall cleaning up and QA.

**Comment by Nidradee** [comment]
this has been completed
